language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: yT1QAOSB6tQ4VgRiabWlfsGoKZvshpzKVZ+3tvZWA+QAz6ETHL8Q72IdfJikcSURNYaG7p3zcRsjtPRf5pQp+doH7WU5mbPpQM2EebqPLPHOmFRoqMsniVhcHLRtiyJjYga3j+eTlcPSNkXuH+kM1P5JnlsTuzUVFM7aVp0xTM9q8n32uj4mYaHS5audzXvLorWXAawEr8jtz+xhRjnjPGNIMUIkTUkFrTUbVF2GgV3asg3c0d0nrA1Xre4WKkByLf4Moy4KwZ28CdiVv2BXflm57V+7xQMqaneyuPGec/i0XFi1AY9YZzPUJXqy/raIu0Ucck6jR33F9GJKaRIzFV2UtY6wYf8uaLh296z4QOLjoX4lilOVmLiXbmcpdlLjC21h2enpQeAUWDwldgYgI/en/VBAquqiSW0Oy8j0adGOCdBlBbFrstSSArI+ON1QfXvQkFoaaQvlX7zd0tBX+vMSeBJTEPhw9yTo/OTX9oA2sK0L0rx2GElA1BBCkbq5drVAnXn27EgkDKQOjcMUT7BYULvsOQQtLp02AYq2/3qR4BMudh4dCrRte48cFATzgZk6X8QpEnid57MKSUrPXt97zlmvwxsLDL/OMUCwHxyaFH5Uto8DB3HkBO6USPv35NJQsIUFg+qwAg1R46I4xIp3sWA4ddY3mlJ1uwBjxe8=
  app: WeddingGiftEx
  on:
    repo: complicationlamp/WeddingGiftEx
